### ISSUE TITLE
Potential cases to consider - not actual reports from beginners/teachers

### ISSUE THREAD

**Issue by aroberge** [aroberge/friendly-traceback#110]
# About new cases

Report of cases not handled by friendly-traceback from code run in "normal" sessions by teachers or student/beginners will be treated in priority, and should be submitted individually as new cases to consider.  Other cases resulting from thinking about what beginners *might* encounter should be added as comment to this issue, to be treated on a lower priority.

An exception to this is when a test case for a known Exception that is already partially covered is submitted because this particular case is not recognized. An example of this is issue #107.

## Cases submitted

- [ ] Using uppercase by mistake; reported as #109 

```
IF FOO:
    BAR()
```

Checking for this should be easy. If the syntax becomes valid after lowercasing the entire program, there's probably a keyword somewhere that was meant to be lowercase.

- [x] Malformed variable names; reported as #108 
Just some thoughts about potential syntax errors which seem unhandled. I don't know if these are actually common mistakes.

- Name containing a space, e.g. `my name = "Alex"`
- Name containing a dash, e.g. `my-name = "Alex"`. There is a special message for this but maybe it could suggest underscores instead of `-`.
- Name starting with a number, e.g. `2x = 3` or `2pi * r`. In the former case one would point out that this is just an invalid name, in the latter one might suggest `2 * pi`.

- [ ] #99 Improved Error message for "Unhashable type"
See https://mail.python.org/archives/list/python-ideas@python.org/message/B6OMGYIM47OVGOCZLEY3MEUJDFURJRDV/

**Comment by aroberge** [comment]
```python
import os.pathh
```
```pytb
ModuleNotFoundError: No module named 'os.pathh'; 'os' is not a package
```

**Comment by alexmojaki** [comment]
```
# Trying to access a nested list with (row, column) coordinates
>>> [][1, 2]
TypeError: list indices must be integers or slices, not tuple 

# Forgot to convert input() to int
# maybe there could be a generic check for TypeError that mentions both str and int (or integer)
>>> []["1"]
TypeError: list indices must be integers or slices, not str 
>>> range("3")
TypeError: 'str' object cannot be interpreted as an integer 
```

**Comment by aroberge** [comment]
Thanks, I will definitely have to include these.

**Comment by aroberge** [comment]
https://bugs.python.org/issue42209 f-string SyntaxError example; handled differently depending on the Python version.

**Comment by aroberge** [comment]
object cannot be interpreted as an integer is now recognized and some analysis is performed so that objects that can be converted into integers are recognized. Translation remains to be done.
![image](https://user-images.githubusercontent.com/629698/102403871-45f53a00-3fbd-11eb-9b6d-1226648f2c22.png)

**Comment by alexmojaki** [comment]
Nice!

Just noticed a typo: "or by tring"

**Comment by aroberge** [comment]
Thanks; typo fixed locally. I need to update the translations.

`Executing` is **extremely** helpful in narrowing down the part of the
source to analyze, and simplifying the analysis where the problematic code
spans more than one line.

I've also monkeypatched `pure_eval` to add a method so that relevant
literals can be identified, as shown in this last example.

I will need to revise all existing examples and see if I can make use of
`Executing` and `pure_eval` to give better explanations.

**Comment by aroberge** [comment]
The three malformed names are now supported.
- name with space: `my name = "Al"`
- name with minus instead of underscore, `my-name` instead of `my_name`
- names that begin with a number

Here are some screen captures.

![image](https://user-images.githubusercontent.com/629698/102894141-086b3380-4439-11eb-8582-eef449c9ffd8.png)

![image](https://user-images.githubusercontent.com/629698/102894211-26389880-4439-11eb-8cfa-057f7189d665.png)

![image](https://user-images.githubusercontent.com/629698/102894341-52ecb000-4439-11eb-88d8-84cc8599ad86.png)


For the first one (a space between names), it could be that a comma is missing (unpacking), a period is missing, an underscore is missing, that the space should be removed altogether, etc.

As for the "all uppercase by mistake", I can't imagine this to be frequent enough to justify trying to handle it.

**Comment by alexmojaki** [comment]
Excellent stuff!

> For the first one (a space between names), it could be that a comma is missing (unpacking), a period is missing, an underscore is missing, that the space should be removed altogether, etc.

Yes, but in most of those cases the programmer will likely know what to do. The most vulnerable user is the complete beginner who doesn't understand that names are not allowed to contain spaces. I think in addition to the current message it would be good to add underneath:

> Note that variable names are not allowed to contain spaces. You can join words with an underscore, e.g. my_name

Similarly you could also have

>  Note that variable names are not allowed to start with a number

For the upper/lower case issue, I gave a poor example. I don't think they would forget that they had caps lock on, but they might write:

```python
For i in range(3):
```

But yes, I don't know how common that is.

**Comment by aroberge** [comment]
> Excellent stuff!
> 
> > For the first one (a space between names), it could be that a comma is missing (unpacking), a period is missing, an underscore is missing, that the space should be removed altogether, etc.
> 
> Yes, but in most of those cases the programmer will likely know what to do. The most vulnerable user is the complete beginner who doesn't understand that names are not allowed to contain spaces. I think in addition to the current message it would be good to add underneath:
> 
> > Note that variable names are not allowed to contain spaces. You can join words with an underscore, e.g. my_name
> 

This is what I have currently for a detailed explanation, following various "playful experiments" at the repl.
![image](https://user-images.githubusercontent.com/629698/102897928-29cf1e00-443f-11eb-9265-09a5964f233a.png)


It is already getting rather long. Perhaps I could add a sentence like: "Perhaps you forgot that variable names are not allowed to contain spaces."

Ideally, I would like intermediate users as well as beginners to make find Friendly-traceback useful. If I have messages written strictly with absolute beginners in mind, it might defeat the purpose.

> Similarly you could also have
> 
> > Note that variable names are not allowed to start with a number
> 

Already taken care of with the detailed explanation:

![image](https://user-images.githubusercontent.com/629698/102898386-d14c5080-443f-11eb-970f-184b19399868.png)


> For the upper/lower case issue, I gave a poor example. I don't think they would forget that they had caps lock on, but they might write:
> 
> ```python
> For i in range(3):
> ```
> 
> But yes, I don't know how common that is.

**Comment by aroberge** [comment]
For spaces between names: if the space occurs between the first token (name) and the second on that line and if there is an `=` sign on that line, I've added the sentence "Or perhaps you forgot that you cannot have spaces in variable names." 

Other cases with space between identifiers can occur when one forget a comma on a multi-line list/set/tuple, or for tuple unpacking, etc.  There are too many cases for me to have a hope to disambiguate them all - but I like your suggestion about variable names not containing spaces.

**Comment by aroberge** [comment]
Closing this issue: other than the hypothetical problem with using uppercase letters in keywords, all potential cases mentioned here should be handled properly, and are included in the latest version uploaded to pypi.
