### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by aroberge** [aroberge/friendly-traceback#137]
# Rough roadmap

- [ ] Periodically review https://github.com/python/cpython/blob/master/Lib/test/test_syntax.py

## Goal for version 0.3

Confirm complete support for

- [ ] AttributeError
- [ ] FileNotFoundError
- [ ] ImportError
- [x] IndentationError
  - [x] Try to identify incorrect type of error when it is cause by a missing continuation character.
- [ ] IndexError
- [ ] ModuleNotFoundError
- [ ] NameError
- [x] TabError
- [ ] UnboundLocalError
- [ ] Check https://mail.python.org/archives/list/python-ideas@python.org/message/LQVK2UKPSOI2AHYFUWK6ZII2U6QKK6BP/ for various unicode related errors

- [ ] Have a look at https://github.com/elifiner/affirm to see if there could be useful for dealing with AssertionError cases.

Currently, as far as I know, all potential messages for the above cases have been identified and, other than for IndexError, analysis of potential cause (e.g. typo in name of attribute) have been implemented. However, this needs to be further verified.

Signficant support for SyntaxError
- [ ] Be able to identify essentially all messages (different from `SyntaxError: invalid syntax`) and provide explanation
- [ ] Be able to suggest a fix for all `SyntaxError: invalid syntax` that are due to a single cause (e.g. misplaced or missing token, or incorrect token.
- [x] Investigate separating out the statement analyzer into different files, focusing on one type of statement (in particular, `def`)
- [ ] Investigate doing two passes of statement analyzer, first trying to find a perfect fix, then redoing an identifying apparent fix of error (but other error later in statement).

Also, support for
- [ ] Raise from other error

## Goal for version 0.4
Include full support for
- [ ] TypeError
- [ ] ValueError
and include generic information for at least 10 other types of errors.

- [ ] Confirm that usage in IPython environments is reliable.

## Longer term goals (release 1.0)

- [ ] Include support for all standard types of errors
- [ ] Include support for Warnings in additions to Errors.
- [ ] Better color scheme and support for IPython console and Jupyter notebooks and lab
- [ ] Include support for various colour schemes ?
- [ ] Have obtained contributions for supporting at least one more language in addition to French and English.
- [ ] Be able to make suggestions for fixing more complex SyntaxErrors.
