### ISSUE TITLE
Contributors and tasks related to the contest.

### ISSUE THREAD

**Issue by aroberge** [aroberge/friendly-traceback#145]
- [x] Issue #144: `AttributeError` and usage of `__slots__` by at_carreau
- [x] Issue #149 by @dcambie - worth 2 points (two problems)
- ~~[ ] Issue #148 TypeError case by @dcambie~~
- [x] Issue #152 ordering of starred args by @sdementen
- [x] issue #152  using symbol (e.g. `=`) instead of name as function argument by @sdementen
- [x] issue #152 special case of above with `/` which is valid for Python 3.8+, by @sdementen
- [x] issue #152 tuple unpacking in function arguments, by @sdementen. 
   - [x] second example given for the above; I have to determine if this is a different entry for the contest or belongs to the same class of examples.  At first glance, it looks like it might be two different cases, given the different explanations suggested. Additional case by @sdementen
 - [x] issue #152, AttributeError for tuple of length 1 due to spurious comma. by @sdementen
 - [x] ZeroDivisionError reported by @tomerv in issue #141 - worth two points given the reference to StackOverflow.
 - [x] issue #154 by @tomerv `def f(1)`
 - [x] issue #155 unescaped `\` as last string token by @gdementen
 - [x] issue #156 quoted function names by @gdementen
 - [x] issue #157 missing continuation in multi line string by @gdementen
 - [x] issue #158 importing as tuples by @dominik1123
 - [x] issue #159 `and` instead of comma in import statement by @dominik1123
 - [x] issue #160 leading zeros... by @dominik1123  - worth two points given the reference to StackOverflow
 - ~~[ ] issue #162 improved KeyError by @dominik1123~~
 - [x] issue #163 f-string containing backslash by @dominik1123 - worth two points.
 - ~~[ ] issue #164 KeyError/AttributeError for `str.format` by @dominik1123~~
 - [x] issue #167 missing parentheses for tuples in comprehension by @dominik1123 - two points
 - [x] issue #168 multiple exception types require parentheses by @dominik1123 - two points
 - [x] issue #169 misplace if/else in comprehension by @dominik1123 - two points.
 - [x] issue #171 annotated name can't be global by @tomerv -- two points (unrecognized message **and** bug in Friendly-traceback)
 - [x] issue #173 illegal string prefix combination by @dominik1123 - 2 points.
 - [x] issue #176 assign to keyword by @dominik1123
 - [x] issue #178 cannot delete X by @dominik1123
 - ~~[ ] issue #179 keyword arguments inside subscript by @dominik1123~~
